name: martin_pulgar_demo
description: A demo for uploading photos and other info
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.5
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.3
  mockito: ^5.4.2
  dio: ^5.3.0
  get_it: ^7.6.0
  image_picker: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5

flutter:
  uses-material-design: true
  generate: true

flutter_intl:
  enabled: true